/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { StockExchangeService } from "../stockExchange.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { StockExchangeCreateInput } from "./StockExchangeCreateInput";
import { StockExchange } from "./StockExchange";
import { StockExchangeFindManyArgs } from "./StockExchangeFindManyArgs";
import { StockExchangeWhereUniqueInput } from "./StockExchangeWhereUniqueInput";
import { StockExchangeUpdateInput } from "./StockExchangeUpdateInput";
import { StockFindManyArgs } from "../../stock/base/StockFindManyArgs";
import { Stock } from "../../stock/base/Stock";
import { StockWhereUniqueInput } from "../../stock/base/StockWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class StockExchangeControllerBase {
  constructor(
    protected readonly service: StockExchangeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: StockExchange })
  @nestAccessControl.UseRoles({
    resource: "StockExchange",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createStockExchange(
    @common.Body() data: StockExchangeCreateInput
  ): Promise<StockExchange> {
    return await this.service.createStockExchange({
      data: data,
      select: {
        address: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [StockExchange] })
  @ApiNestedQuery(StockExchangeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "StockExchange",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async stockExchanges(
    @common.Req() request: Request
  ): Promise<StockExchange[]> {
    const args = plainToClass(StockExchangeFindManyArgs, request.query);
    return this.service.stockExchanges({
      ...args,
      select: {
        address: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: StockExchange })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "StockExchange",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async stockExchange(
    @common.Param() params: StockExchangeWhereUniqueInput
  ): Promise<StockExchange | null> {
    const result = await this.service.stockExchange({
      where: params,
      select: {
        address: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: StockExchange })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "StockExchange",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateStockExchange(
    @common.Param() params: StockExchangeWhereUniqueInput,
    @common.Body() data: StockExchangeUpdateInput
  ): Promise<StockExchange | null> {
    try {
      return await this.service.updateStockExchange({
        where: params,
        data: data,
        select: {
          address: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: StockExchange })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "StockExchange",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteStockExchange(
    @common.Param() params: StockExchangeWhereUniqueInput
  ): Promise<StockExchange | null> {
    try {
      return await this.service.deleteStockExchange({
        where: params,
        select: {
          address: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/stocks")
  @ApiNestedQuery(StockFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Stock",
    action: "read",
    possession: "any",
  })
  async findStocks(
    @common.Req() request: Request,
    @common.Param() params: StockExchangeWhereUniqueInput
  ): Promise<Stock[]> {
    const query = plainToClass(StockFindManyArgs, request.query);
    const results = await this.service.findStocks(params.id, {
      ...query,
      select: {
        company: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        sharePrice: true,

        stockExchange: {
          select: {
            id: true,
          },
        },

        ticketSymbol: true,
        totalShares: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/stocks")
  @nestAccessControl.UseRoles({
    resource: "StockExchange",
    action: "update",
    possession: "any",
  })
  async connectStocks(
    @common.Param() params: StockExchangeWhereUniqueInput,
    @common.Body() body: StockWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stocks: {
        connect: body,
      },
    };
    await this.service.updateStockExchange({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/stocks")
  @nestAccessControl.UseRoles({
    resource: "StockExchange",
    action: "update",
    possession: "any",
  })
  async updateStocks(
    @common.Param() params: StockExchangeWhereUniqueInput,
    @common.Body() body: StockWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stocks: {
        set: body,
      },
    };
    await this.service.updateStockExchange({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/stocks")
  @nestAccessControl.UseRoles({
    resource: "StockExchange",
    action: "update",
    possession: "any",
  })
  async disconnectStocks(
    @common.Param() params: StockExchangeWhereUniqueInput,
    @common.Body() body: StockWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stocks: {
        disconnect: body,
      },
    };
    await this.service.updateStockExchange({
      where: params,
      data,
      select: { id: true },
    });
  }
}
